make:
	g++ -std=c++11 -Wall -Wextra -I. -I./Armas -I./Armas/Combate/Headers -o prueba_armas main.cpp Armas/Combate/Sources/ArmaCombate.cpp Armas/Combate/Sources/espada.cpp

clean:
	rm -f prueba_armas

.PHONY: make clean
