make:
	g++ -std=c++11 -Wall -Wextra -I. -I./Armas -I./Armas/Combate/Headers -o prueba_armas main.cpp \
	Armas/Combate/Sources/ArmaCombate.cpp \
	Armas/Combate/Sources/espada.cpp \
	Armas/Combate/Sources/garrote.cpp \
	Armas/Combate/Sources/hacha_doble.cpp \
	Armas/Combate/Sources/hacha_simple.cpp \
	Armas/Combate/Sources/lanza.cpp

clean:
	rm -f prueba_armas

.PHONY: make clean
